[window.padding]
x = 15
y = 15

[font]
size = 15.0

[font.normal]
family = "PxPlus IBM VGA 8x16"
style = "Regular"

[font.bold]
family = "PxPlus IBM VGA 8x16"
style = "Bold"

[colors.primary]
background = "#9c9a9d"
foreground = "#00009c"

[colors.normal]
black =   "#000000"
red =     "#00009c"
green =   "#00009c"
yellow =  "#00009c"
blue =    "#00009c"
magenta = "#00009c"
cyan =    "#00009c"
white =   "#00009c"

[colors.bright]
black =   "#00009c"
red =     "#00009c"
green =   "#00009c"
yellow =  "#00009c"
blue =    "#00009c"
magenta = "#00009c"
cyan =    "#00009c"
white =   "#00009c"
